
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: MYSQL
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sbt_activiti?characterEncoding=utf-8
    username: root
    password: db2